#####################################################

#             Création serveur web                  #

#       Avec: Apache + php + ssh2 + mysql

# Pour lancer en arrière plan: $ docker-compose up -d

#####################################################

# Liens:

#       - ssh2
#       http://lindev.fr/?post/2009/01/19/Installer-le-module-SSH2-pour-php
#       - Docker compose second exemple: 
#       https://tech.gamuza.fr/docker-les-commandes-de-base
#       - Docker compose premier exemple:
#       https://www.metal3d.org/ticket/docker-apache-mysql-php
#

#####################################################

# Install SSH par défaut ?

apache:
    image: skulblaka/apache:latest
    volumes:
    - "./src/www:/var/www/html"
    - "./src/php/modules:/usr/local/lib/php/extensions/no-debug-non-zts-20151012"
    - "./src/php/conf:/usr/local/etc/php/conf.d"
    - "./src/apache2/sites-available:/etc/apache2/sites-available"
    - "./src/apache2/sites-enabled:/etc/apache2/sites-enabled"
    - "./src/apache2/mods-enabled:/etc/apache2/mods-enabled"
    - "./src/keys:/etc/apache2/keys"
    ports:
    - "80:80"
    - "443:443"
    environment:
    - ALLOW_OVERRIDE=true
    links:
#    - "mariadb:db"
    - mysql
#   privileged: true

mysql:
    image: skulblaka/mysql:latest
    ports:
    - "3306:3306"
    volumes:
    - "./src/mysql/data/:/var/lib/mysql"
    - "./src/mysql/dump:/dump"
    environment:
    - MYSQL_ROOT_PASSWORD=$ANSIBLE_VAULT;1.1;AES256
65386631383761316230633639306161623335326332613265343966396333636364653936656631
3933383130343734363462376131653436363562643462350a626564613137353234303836356130
63613138336265613231346365376131616464613765626438393033336534373734636431616432
3439663762613361340a313434386331316364363362336335363664626538376230386661623561
6363
    privileged: true

#phpmyadmin:     --- NOT WORKING ---
#  image: phpmyadmin/phpmyadmin
#  ports:
#    - "8081:8080"
#  environment:
#    - MYSQL_ROOT_PASSWORD=password
#  links:
#    - "mariadb:db"

# mariadb:
#   image: skulblaka/mariadb:10.0
#   environment:
#     - MYSQL_ROOT_PASSWORD=password
#     - TERM=dumb
#   volumes:
#     - "./src/mysql/data:/var/lib/mysql"
#     - "./src/mysql/dump:/dump"




